<a href="https://colab.research.google.com/github/saifmdev/MachineLearningAtoZ/blob/main/SAIF_data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the dataset

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the libraries

In [2]:
dataset = pd.read_csv('/content/drive/MyDrive/OnlineCourses/Udemy/MachineLearningAZ/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Python/Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

In [6]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [7]:
from sklearn.compose import ColumnTransformer #Import Sklearn, Colum Transformer
from sklearn.preprocessing import OneHotEncoder #Import Sklearn One Hot Encoder
ct = ColumnTransformer( transformers=[ ( 'encoder' , OneHotEncoder() , [0] ) ] , remainder = 'passthrough' ) #Create instance of Column transformer and set the parameters
X = np.array(ct.fit_transform(X)) #Set X to be the result of fit_transform(X) casted to numpy array type

In [8]:
print(X) #Encoded Columns, Binary vectors

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [9]:
from sklearn.preprocessing import LabelEncoder #Import Sklearn Label Encoder
le = LabelEncoder() #Make instance of Label Encoder
y = le.fit_transform(y) #Assign y to become new values returned from fir_transform method

In [11]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [15]:
from sklearn.model_selection import train_test_split #IMport Sklearn train test split
X_train, X_test, y_train, y_test = train_test_split( X , y , test_size = 0.3, random_state = 1 ) #create test set and train set using the return from instance of train_test_split method

## Feature Scaling 
####->Scaling all Features, making sure they all take values in a similar scale

In [21]:
from sklearn.preprocessing import StandardScaler #Used for Feature Scaling
sc = StandardScaler() #create instance of StandardScaler
X_train[:,3:] = sc.fit_transform(X_train[:,3:]) #fit and transform the Training Set Only
X_test[:,3:] = sc.transform(X_test[:,3:])# The Test set must only be transfomed but not fitted to model

In [22]:
print(X_train)

[[0.0 1.0 0.0 -0.038910211282047996 -0.22960023388015188]
 [1.0 0.0 0.0 0.5058327466666259 0.49120534884662787]
 [0.0 0.0 1.0 -0.3112816902563849 -0.4731156334500103]
 [0.0 0.0 1.0 -1.809324824615238 -1.6127677034369463]
 [1.0 0.0 0.0 1.0505757046152997 1.1048641557626704]
 [0.0 1.0 0.0 1.3229471835896367 1.455526331143266]
 [1.0 0.0 0.0 -0.7198389087178904 -0.736112264985457]] [[0.0 1.0 0.0 -1.4007676061537326 -1.0867744403660526]
 [1.0 0.0 0.0 -0.4474674297435534 0.05287762962088326]
 [0.0 0.0 1.0 -0.20535944843303158 -1.2621055280563505]]


In [23]:
print(X_test)

[[0.0 1.0 0.0 -1.4007676061537326 -1.0867744403660526]
 [1.0 0.0 0.0 -0.4474674297435534 0.05287762962088326]
 [0.0 0.0 1.0 -0.20535944843303158 -1.2621055280563505]]
